# Generated by Django 6.0.8 on 2026-08-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('org', 'Organization'), ('person', 'Person')], max_length=10)),
                ('display_name', models.CharField(max_length=500)),
                ('match_key', models.CharField(db_index=True, max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'match_key'], name='entities_en_entity__145424_idx')],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(max_length=200)),
                ('source_url', models.URLField(max_length=1000)),
                ('retrieved_at', models.DateTimeField()),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_system', 'processed'], name='entities_ra_source__543c89_idx')],
            },
        ),
    ]
