# Generated by Django 6.0.8 on 2026-08-06 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000)),
                ('retrieved_at', models.DateTimeField()),
                ('item_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('consideration_type', models.CharField(blank=True, default='', max_length=50)),
                ('wards', models.CharField(blank=True, default='', max_length=200)),
                ('origin_text', models.TextField(blank=True, default='')),
                ('summary_text', models.TextField(blank=True, default='')),
                ('decision_text', models.TextField(blank=True, default='')),
                ('tracking_status_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('adopted', 'Adopted'), ('amended', 'Adopted with amendments'), ('deferred', 'Deferred'), ('not_adopted', 'Not adopted'), ('received', 'Received'), ('referred', 'Referred'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last_considered_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_considered_date'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('pdf_url', models.URLField(max_length=1000)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_documents', to='council.agendaitem')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000)),
                ('retrieved_at', models.DateTimeField()),
                ('tmmis_meeting_id', models.CharField(max_length=50, unique=True)),
                ('body_type', models.CharField(choices=[('council', 'City Council'), ('standing_committee', 'Standing Committee'), ('community_council', 'Community Council'), ('special', 'Special Committee')], max_length=20)),
                ('body_name', models.CharField(max_length=200)),
                ('meeting_number', models.PositiveIntegerField(blank=True, null=True)),
                ('meeting_date', models.DateField()),
            ],
            options={
                'ordering': ['-meeting_date'],
                'indexes': [models.Index(fields=['body_name', 'meeting_date'], name='council_mee_body_na_f7c9b7_idx')],
            },
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='primary_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_items', to='council.meeting'),
        ),
        migrations.CreateModel(
            name='NewsCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('publisher', models.CharField(max_length=200)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(related_name='news_citations', to='council.agendaitem')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.AddIndex(
            model_name='agendaitem',
            index=models.Index(fields=['status', 'last_considered_date'], name='council_age_status_4cb227_idx'),
        ),
    ]
