# Generated by Django 6.0.8 on 2026-08-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='consideration_type',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='wards',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
