# Generated by Django 6.0.8 on 2026-08-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactBudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000)),
                ('retrieved_at', models.DateTimeField()),
                ('budget_type', models.CharField(choices=[('operating', 'Operating'), ('capital', 'Capital')], default='operating', max_length=10)),
                ('fiscal_year', models.PositiveIntegerField()),
                ('program', models.CharField(max_length=300)),
                ('service', models.CharField(blank=True, default='', max_length=300)),
                ('activity', models.CharField(blank=True, default='', max_length=300)),
                ('expense_or_revenue', models.CharField(choices=[('Expenses', 'Expenses'), ('Revenues', 'Revenues')], max_length=10)),
                ('category_name', models.CharField(blank=True, default='', max_length=200)),
                ('sub_category_name', models.CharField(blank=True, default='', max_length=200)),
                ('commitment_item', models.CharField(blank=True, default='', max_length=300)),
                ('amount_cents', models.BigIntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['fiscal_year', 'program'], name='budget_fact_fiscal__33bf06_idx'), models.Index(fields=['budget_type', 'fiscal_year'], name='budget_fact_budget__550de7_idx'), models.Index(fields=['expense_or_revenue'], name='budget_fact_expense_0be713_idx')],
            },
        ),
    ]
