"""
Leave-one-out diagnostics, ENRICHED pass -- identical to diagnostics.py
except it imports from specification_enriched (votes_coded_enriched.csv)
instead of specification. See specification_enriched.py's docstring.
"""
import sys
import warnings
from pathlib import Path

import pandas as pd
import statsmodels.formula.api as smf
from scipy import stats

sys.path.insert(0, str(Path(__file__).resolve().parent))
from specification_enriched import (  # noqa: E402
    BASE_THRESHOLD, DEV_APPS_CSV, DONORS_CSV, VOTES_CODED_CSV,
    compute_dev_affiliation_share, compute_ward_intensity, load_current_members,
)

ROOT = Path(__file__).resolve().parents[2]
RESULT_OUT = ROOT / "phase3-leave-one-out-result-enriched.md"


def main():
    warnings.filterwarnings("ignore")

    current_members = load_current_members()
    donors = pd.read_csv(DONORS_CSV)
    dev_apps = pd.read_csv(DEV_APPS_CSV)
    ward_intensity = compute_ward_intensity(dev_apps)

    mix = compute_dev_affiliation_share(current_members, donors, BASE_THRESHOLD)
    mix = mix.merge(ward_intensity, left_on="ward_number", right_index=True, how="left")
    mix["ward_development_intensity"] = mix["ward_development_intensity"].fillna(0)

    votes = pd.read_csv(VOTES_CODED_CSV)
    votes_included = votes[votes["included"] == True].copy()  # noqa: E712
    current_ids = set(current_members["member_name"])
    votes_primary = votes_included[votes_included["member_id"].isin(current_ids)].copy()

    vote_level = votes_primary.merge(
        mix[["member_id", "dev_affiliation_share", "ward_development_intensity"]],
        on="member_id", how="left",
    )
    vote_level["pro_dev_vote"] = vote_level["pro_dev_vote"].astype(bool).astype(int)
    full_model_df = vote_level.dropna(subset=["dev_affiliation_share", "ward_development_intensity"])

    member_vote_rate = votes_primary.groupby("member_id")["pro_dev_vote"].apply(
        lambda s: s.astype(bool).mean()
    ).rename("pro_dev_vote_rate")
    member_level_full = mix.dropna(subset=["dev_affiliation_share"]).merge(
        member_vote_rate, on="member_id", how="left"
    ).dropna(subset=["pro_dev_vote_rate"])

    members = sorted(full_model_df["member_id"].unique())
    rows = []
    for dropped in members:
        loo_model_df = full_model_df[full_model_df["member_id"] != dropped]
        try:
            model = smf.logit(
                "pro_dev_vote ~ dev_affiliation_share + ward_development_intensity",
                data=loo_model_df,
            ).fit(disp=0, cov_type="cluster", cov_kwds={"groups": loo_model_df["member_id"]})
            ci = model.conf_int().loc["dev_affiliation_share"]
            coef, p, ci_low, ci_high = model.params["dev_affiliation_share"], model.pvalues["dev_affiliation_share"], ci[0], ci[1]
        except Exception as e:  # noqa: BLE001
            coef = p = ci_low = ci_high = None

        loo_member_level = member_level_full[member_level_full["member_id"] != dropped]
        if len(loo_member_level) >= 3:
            rho, srho_p = stats.spearmanr(loo_member_level["dev_affiliation_share"], loo_member_level["pro_dev_vote_rate"])
        else:
            rho = srho_p = None

        rows.append({
            "dropped_member": dropped,
            "logit_coef": coef, "logit_p": p, "logit_ci_low": ci_low, "logit_ci_high": ci_high,
            "spearman_rho": rho, "spearman_p": srho_p,
        })

    loo_df = pd.DataFrame(rows)
    loo_csv = ROOT / "data" / "processed" / "leave_one_out_enriched.csv"
    loo_df.to_csv(loo_csv, index=False)

    coefs = loo_df["logit_coef"].dropna()
    rhos = loo_df["spearman_rho"].dropna()
    sign_flips_logit = (coefs > 0).sum()
    sign_flips_rho = (rhos > 0).sum()

    with RESULT_OUT.open("w", encoding="utf-8") as f:
        f.write("# Phase 3 — Leave-One-Out Diagnostics, ENRICHED\n\n")
        f.write("Generated by pipeline/analyze/diagnostics_enriched.py, base threshold "
                f"({BASE_THRESHOLD}) specification, against votes_coded_enriched.csv.\n\n")
        f.write(f"Full-sample logistic coefficient: see phase3-specification-result-enriched.md\n\n")
        f.write(f"Across {len(coefs)} leave-one-out logistic reruns: "
                f"coefficient range [{coefs.min():.4f}, {coefs.max():.4f}], "
                f"{sign_flips_logit} of {len(coefs)} flip positive when one member is dropped.\n\n")
        f.write(f"Across {len(rhos)} leave-one-out Spearman reruns: "
                f"rho range [{rhos.min():.4f}, {rhos.max():.4f}], "
                f"{sign_flips_rho} of {len(rhos)} flip positive when one member is dropped.\n\n")
        f.write("## Full table\n\n")
        f.write(loo_df.to_string(index=False))
        f.write("\n")

    print(f"LOO logistic coef range: [{coefs.min():.4f}, {coefs.max():.4f}]; "
          f"{sign_flips_logit}/{len(coefs)} flip positive")
    print(f"LOO spearman rho range: [{rhos.min():.4f}, {rhos.max():.4f}]; "
          f"{sign_flips_rho}/{len(rhos)} flip positive")
    print(f"-> {RESULT_OUT}")
    print(f"-> {loo_csv}")


if __name__ == "__main__":
    main()
