"""
Phase 3 sensitivity analysis, ENRICHED pass -- identical to
sensitivity.py except it imports from specification_enriched (votes_coded_
enriched.csv) instead of specification. See specification_enriched.py's
docstring for what "enriched" means and why this is a separate, side-by-
side output rather than a replacement.
"""
import sys
import warnings
from pathlib import Path

import pandas as pd
import statsmodels.formula.api as smf
from scipy import stats

sys.path.insert(0, str(Path(__file__).resolve().parent))
from specification_enriched import (  # noqa: E402
    DEV_APPS_CSV, DONORS_CSV, VOTES_CODED_CSV,
    compute_dev_affiliation_share, compute_ward_intensity,
    load_current_members,
)

ROOT = Path(__file__).resolve().parents[2]
RESULT_OUT = ROOT / "phase3-sensitivity-result-enriched.md"
MIX_ALL_THRESHOLDS_OUT = ROOT / "data" / "processed" / "candidate_donor_mix_all_thresholds_enriched.csv"

THRESHOLDS = {"strict": 0.75, "base": 0.5, "permissive": 0.35}


def run_at_threshold(threshold, current_members, donors, ward_intensity, votes_primary):
    mix = compute_dev_affiliation_share(current_members, donors, threshold)
    mix = mix.merge(ward_intensity, left_on="ward_number", right_index=True, how="left")
    mix["ward_development_intensity"] = mix["ward_development_intensity"].fillna(0)

    vote_level = votes_primary.merge(
        mix[["member_id", "dev_affiliation_share", "ward_development_intensity"]],
        on="member_id", how="left",
    )
    vote_level["pro_dev_vote"] = vote_level["pro_dev_vote"].astype(bool).astype(int)
    model_df = vote_level.dropna(subset=["dev_affiliation_share", "ward_development_intensity"])

    result = {"threshold": threshold, "n_members": mix["dev_affiliation_share"].notna().sum(),
              "n_votes": len(model_df)}
    try:
        model = smf.logit(
            "pro_dev_vote ~ dev_affiliation_share + ward_development_intensity",
            data=model_df,
        ).fit(disp=0, cov_type="cluster", cov_kwds={"groups": model_df["member_id"]})
        ci = model.conf_int().loc["dev_affiliation_share"]
        result.update({
            "coef": model.params["dev_affiliation_share"],
            "p": model.pvalues["dev_affiliation_share"],
            "ci_low": ci[0], "ci_high": ci[1],
        })
    except Exception as e:  # noqa: BLE001
        result.update({"coef": None, "p": None, "ci_low": None, "ci_high": None, "error": str(e)})

    member_level = mix.dropna(subset=["dev_affiliation_share"]).copy()
    member_vote_rate = votes_primary.groupby("member_id")["pro_dev_vote"].apply(
        lambda s: s.astype(bool).mean()
    ).rename("pro_dev_vote_rate")
    member_level = member_level.merge(member_vote_rate, on="member_id", how="left")
    member_level = member_level.dropna(subset=["pro_dev_vote_rate"])
    if len(member_level) >= 3:
        rho, p = stats.spearmanr(member_level["dev_affiliation_share"], member_level["pro_dev_vote_rate"])
        result["spearman_rho"] = rho
        result["spearman_p"] = p
    else:
        result["spearman_rho"] = result["spearman_p"] = None

    mix["threshold_setting"] = threshold
    return result, mix


def main():
    warnings.filterwarnings("ignore")

    current_members = load_current_members()
    donors = pd.read_csv(DONORS_CSV)
    dev_apps = pd.read_csv(DEV_APPS_CSV)
    ward_intensity = compute_ward_intensity(dev_apps)

    votes = pd.read_csv(VOTES_CODED_CSV)
    votes_included = votes[votes["included"] == True].copy()  # noqa: E712
    current_ids = set(current_members["member_name"])
    votes_primary = votes_included[votes_included["member_id"].isin(current_ids)].copy()

    results = []
    all_mixes = []
    for label, threshold in THRESHOLDS.items():
        r, mix = run_at_threshold(threshold, current_members, donors, ward_intensity, votes_primary)
        r["label"] = label
        results.append(r)
        all_mixes.append(mix)

    pd.concat(all_mixes, ignore_index=True).to_csv(MIX_ALL_THRESHOLDS_OUT, index=False)

    directions = []
    for r in results:
        if r["coef"] is None:
            directions.append(None)
        else:
            directions.append("positive" if r["coef"] > 0 else ("negative" if r["coef"] < 0 else "zero"))
    direction_flips = len(set(d for d in directions if d is not None)) > 1

    with RESULT_OUT.open("w", encoding="utf-8") as f:
        f.write("# Phase 3 — Sensitivity Analysis (strict / base / permissive), ENRICHED\n\n")
        f.write("Generated by pipeline/analyze/sensitivity_enriched.py against votes_coded_enriched.csv. "
                "Reported alongside, not instead of, phase3-sensitivity-result.md.\n\n")
        f.write("| Threshold | Setting | n members | n votes | coef | p | 95% CI | Spearman rho | Spearman p |\n")
        f.write("|---|---|---|---|---|---|---|---|---|\n")
        for r in results:
            coef_s = f"{r['coef']:.4f}" if r["coef"] is not None else "—"
            p_s = f"{r['p']:.4f}" if r["p"] is not None else "—"
            ci_s = f"[{r['ci_low']:.4f}, {r['ci_high']:.4f}]" if r["ci_low"] is not None else "—"
            rho_s = f"{r['spearman_rho']:.4f}" if r["spearman_rho"] is not None else "—"
            srp_s = f"{r['spearman_p']:.4f}" if r["spearman_p"] is not None else "—"
            f.write(f"| {r['threshold']} | {r['label']} | {r['n_members']} | {r['n_votes']} | "
                    f"{coef_s} | {p_s} | {ci_s} | {rho_s} | {srp_s} |\n")
        f.write(f"\n**Direction flips across thresholds: {direction_flips}** "
                f"(directions observed: {directions})\n\n")
        f.write("## Per-threshold detail\n\n")
        for r in results:
            f.write(f"### {r['label']} (threshold={r['threshold']})\n\n")
            f.write(f"- n members with defined share: {r['n_members']}\n")
            f.write(f"- n included vote rows in model: {r['n_votes']}\n")
            if r["coef"] is not None:
                f.write(f"- dev_affiliation_share coefficient: {r['coef']:.4f} (p={r['p']:.4f}), "
                        f"95% CI [{r['ci_low']:.4f}, {r['ci_high']:.4f}]\n")
                f.write(f"- Spearman rho={r['spearman_rho']:.4f}, p={r['spearman_p']:.4f}\n")
            else:
                f.write(f"- MODEL ERROR: {r.get('error')}\n")
            f.write("\n")

    print(f"Direction flips across thresholds: {direction_flips}")
    for r in results:
        if r["coef"] is not None:
            print(f"{r['label']:10s} (t={r['threshold']}): coef={r['coef']:.4f} p={r['p']:.4f} "
                  f"CI=[{r['ci_low']:.4f},{r['ci_high']:.4f}]  spearman rho={r['spearman_rho']:.4f} p={r['spearman_p']:.4f}")
        else:
            print(f"{r['label']:10s} (t={r['threshold']}): ERROR {r.get('error')}")
    print(f"-> {RESULT_OUT}")
    print(f"-> {MIX_ALL_THRESHOLDS_OUT}")


if __name__ == "__main__":
    main()
