# Generated by Django 6.0.8 on 2026-08-05 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactLobbyingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000)),
                ('retrieved_at', models.DateTimeField()),
                ('subject_matter_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('registrant_type', models.CharField(choices=[('In-house', 'In-house'), ('Consultant', 'Consultant'), ('Voluntary', 'Voluntary Unpaid')], max_length=20)),
                ('registrant_position_title', models.CharField(blank=True, default='', max_length=300)),
                ('subject_matter', models.CharField(blank=True, default='', max_length=300)),
                ('particulars', models.TextField(blank=True, default='')),
                ('initial_approval_date', models.DateField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('proposed_start_date', models.DateField(blank=True, null=True)),
                ('proposed_end_date', models.DateField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lobbying_registrations_as_beneficiary', to='entities.entity')),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lobbying_registrations_as_firm', to='entities.entity')),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lobbying_registrations_as_registrant', to='entities.entity')),
            ],
        ),
        migrations.CreateModel(
            name='FactLobbyingCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000)),
                ('retrieved_at', models.DateTimeField()),
                ('poh_office', models.CharField(blank=True, default='', max_length=300)),
                ('poh_type', models.CharField(blank=True, default='', max_length=100)),
                ('poh_position', models.CharField(blank=True, default='', max_length=300)),
                ('poh_name', models.CharField(blank=True, default='', max_length=300)),
                ('communication_method', models.CharField(blank=True, default='', max_length=100)),
                ('communication_date', models.DateField(blank=True, null=True)),
                ('lobbyist_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lobbying_contacts_made', to='entities.entity')),
                ('poh_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lobbying_contacts_received', to='entities.entity')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='lobbying.factlobbyingregistration')),
            ],
        ),
        migrations.AddIndex(
            model_name='factlobbyingregistration',
            index=models.Index(fields=['registrant_type', 'status'], name='lobbying_fa_registr_eb4c86_idx'),
        ),
        migrations.AddIndex(
            model_name='factlobbyingcommunication',
            index=models.Index(fields=['communication_date'], name='lobbying_fa_communi_6ffdd7_idx'),
        ),
    ]
