# Generated by Django 6.0.8 on 2026-08-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factlobbyingcommunication',
            name='communication_method',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
