# Generated by Django 6.0.8 on 2026-08-05 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0002_alter_entity_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000)),
                ('retrieved_at', models.DateTimeField()),
                ('fiscal_year', models.PositiveIntegerField()),
                ('funding_program_code', models.CharField(max_length=20)),
                ('funding_program_name', models.CharField(blank=True, default='', max_length=300)),
                ('division', models.CharField(blank=True, default='', max_length=300)),
                ('recipient_name_raw', models.CharField(max_length=500)),
                ('ward', models.CharField(blank=True, default='', max_length=200)),
                ('service_area', models.CharField(blank=True, default='', max_length=50)),
                ('total_number_of_grants', models.PositiveIntegerField(default=1)),
                ('amount_cents', models.BigIntegerField()),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants_received', to='entities.entity')),
            ],
            options={
                'indexes': [models.Index(fields=['fiscal_year', 'funding_program_code'], name='grants_fact_fiscal__2de4d2_idx'), models.Index(fields=['funding_program_code'], name='grants_fact_funding_f6c17a_idx')],
            },
        ),
    ]
