# Generated by Django 6.0.8 on 2026-08-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factgrant',
            name='funding_program_code',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='factgrant',
            name='ward',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
